import { createKnowledgeDocument } from "./KnowledgeHelpers";
import { buildMetadata } from "./KnowledgeMetadata";
import { KNOWLEDGE_DOMAIN } from "./KnowledgeTypes";

const D = KNOWLEDGE_DOMAIN;

/** Mock knowledge corpus — all domains, no backend */
export const MOCK_KNOWLEDGE_DOCUMENTS = [
  createKnowledgeDocument({
    id: "prod-001",
    domain: D.PRODUCT,
    title: "Premium Running Sneakers",
    summary: "Lightweight sneakers popular across East Africa.",
    content: "Breathable mesh upper, rubber sole, sizes 38–45. Best for daily wear and light jogging.",
    keywords: ["sneakers", "running", "shoes", "footwear"],
    tags: ["trending", "fashion"],
    relationships: [
      { targetId: "cat-footwear", domain: D.CATEGORY, label: "Footwear" },
      { targetId: "brand-yebone", domain: D.BRAND, label: "Yebone Sport" },
      { targetId: "vendor-kigali", domain: D.VENDOR, label: "Kigali Sports Hub" },
    ],
    metadata: buildMetadata({ sku: "SNK-001" }),
    priority: 80,
  }),
  createKnowledgeDocument({
    id: "vendor-kigali",
    domain: D.VENDOR,
    title: "Kigali Sports Hub",
    summary: "Verified vendor specializing in athletic wear.",
    content: "4.8 rating, 1,200+ orders, fast dispatch within Kigali.",
    keywords: ["vendor", "sports", "kigali"],
    tags: ["verified"],
    relationships: [{ targetId: "prod-001", domain: D.PRODUCT, label: "Premium Running Sneakers" }],
    metadata: buildMetadata({ vendorId: "v-101" }),
    priority: 70,
  }),
  createKnowledgeDocument({
    id: "cat-footwear",
    domain: D.CATEGORY,
    title: "Footwear",
    summary: "Shoes, sandals, and sneakers for all ages.",
    content: "Top category on Yebone with seasonal promotions.",
    keywords: ["category", "footwear", "shoes"],
    relationships: [{ targetId: "brand-yebone", domain: D.BRAND, label: "Yebone Sport" }],
    metadata: buildMetadata({ categoryId: "c-foot" }),
    priority: 65,
  }),
  createKnowledgeDocument({
    id: "brand-yebone",
    domain: D.BRAND,
    title: "Yebone Sport",
    summary: "House brand for athletic and casual wear.",
    content: "Quality-focused brand with Africa-wide appeal.",
    keywords: ["brand", "sport", "yebone"],
    relationships: [{ targetId: "cat-footwear", domain: D.CATEGORY, label: "Footwear" }],
    metadata: buildMetadata({ brandId: "b-yebone" }),
    priority: 60,
  }),
  createKnowledgeDocument({
    id: "rev-001",
    domain: D.REVIEW,
    title: "Customer review: Great comfort",
    summary: "5-star review for Premium Running Sneakers.",
    content: "Comfortable for long walks. True to size. Would buy again.",
    keywords: ["review", "comfort", "sneakers"],
    relationships: [{ targetId: "prod-001", domain: D.PRODUCT, label: "Premium Running Sneakers" }],
    metadata: buildMetadata({ rating: 5 }),
    priority: 55,
  }),
  createKnowledgeDocument({
    id: "ship-rw",
    domain: D.SHIPPING,
    title: "Rwanda standard delivery",
    summary: "2–5 business days within Kigali, 5–10 nationwide.",
    content: "Free shipping over 50,000 RWF. Tracking provided.",
    keywords: ["shipping", "delivery", "rwanda"],
    relationships: [{ targetId: "pol-shipping", domain: D.POLICY, label: "Shipping Policy" }],
    metadata: buildMetadata({ zone: "RW" }),
    priority: 75,
  }),
  createKnowledgeDocument({
    id: "pol-shipping",
    domain: D.POLICY,
    title: "Shipping Policy",
    summary: "Marketplace shipping terms and carrier rules.",
    content: "Vendors must ship within 48 hours. Buyers receive tracking links.",
    keywords: ["policy", "shipping", "terms"],
    relationships: [{ targetId: "faq-ship", domain: D.FAQ, label: "Shipping FAQ" }],
    metadata: buildMetadata({ policyType: "shipping" }),
    priority: 70,
  }),
  createKnowledgeDocument({
    id: "faq-ship",
    domain: D.FAQ,
    title: "How long does delivery take?",
    summary: "FAQ about delivery timelines across Africa.",
    content: "Delivery times vary by region. Check product page for vendor-specific estimates.",
    keywords: ["faq", "delivery", "how long"],
    relationships: [{ targetId: "ship-rw", domain: D.SHIPPING, label: "Rwanda delivery" }],
    metadata: buildMetadata({ faqCategory: "shipping" }),
    priority: 68,
  }),
  createKnowledgeDocument({
    id: "comm-001",
    domain: D.COMMISSION,
    title: "Referral commission tiers",
    summary: "Commission structure for marketplace referrals.",
    content: "Tier 1: 5%, Tier 2: 7%, Tier 3: 10% on qualifying orders.",
    keywords: ["commission", "referral", "earnings"],
    relationships: [{ targetId: "ref-001", domain: D.REFERRAL, label: "Referral program" }],
    metadata: buildMetadata({ tier: "standard" }),
    priority: 50,
    visibility: "vendor",
  }),
  createKnowledgeDocument({
    id: "ref-001",
    domain: D.REFERRAL,
    title: "Yebone Referral Program",
    summary: "Share links and earn on referred purchases.",
    content: "Unique referral codes track conversions. Payouts monthly.",
    keywords: ["referral", "share", "earn"],
    relationships: [{ targetId: "comm-001", domain: D.COMMISSION, label: "Commission tiers" }],
    metadata: buildMetadata({ program: "standard" }),
    priority: 50,
  }),
  createKnowledgeDocument({
    id: "ret-001",
    domain: D.RETURNS,
    title: "7-day return window",
    summary: "Standard return policy for most products.",
    content: "Items must be unused with tags. Refund within 14 days of approval.",
    keywords: ["returns", "refund", "policy"],
    relationships: [{ targetId: "pol-shipping", domain: D.POLICY, label: "Shipping Policy" }],
    metadata: buildMetadata({ windowDays: 7 }),
    priority: 72,
  }),
  createKnowledgeDocument({
    id: "mkt-001",
    domain: D.MARKETPLACE,
    title: "Yebone marketplace overview",
    summary: "Pan-African e-commerce platform connecting buyers and vendors.",
    content: "Multi-vendor marketplace with flash sales, auctions, and events.",
    keywords: ["marketplace", "yebone", "africa"],
    relationships: [{ targetId: "evt-001", domain: D.EVENT, label: "Spring Sale Event" }],
    metadata: buildMetadata({ platform: "yebone" }),
    priority: 90,
  }),
  createKnowledgeDocument({
    id: "fash-001",
    domain: D.FASHION,
    title: "Spring 2026 fashion trends",
    summary: "Neutral tones, lightweight layers, and sustainable fabrics.",
    content: "YEBO recommends earth tones and breathable cotton blends this season.",
    keywords: ["fashion", "trends", "spring", "style"],
    relationships: [{ targetId: "prod-001", domain: D.PRODUCT, label: "Premium Running Sneakers" }],
    metadata: buildMetadata({ season: "spring-2026" }),
    priority: 75,
  }),
  createKnowledgeDocument({
    id: "cust-001",
    domain: D.CUSTOMER,
    title: "Customer shopping profile",
    summary: "Mock customer preferences for personalization.",
    content: "Prefers footwear, budget 30K–80K RWF, shops weekly.",
    keywords: ["customer", "profile", "preferences"],
    metadata: buildMetadata({ segment: "active-shopper" }),
    priority: 45,
    visibility: "internal",
  }),
  createKnowledgeDocument({
    id: "ord-001",
    domain: D.ORDER,
    title: "Order lifecycle",
    summary: "From cart to delivery — order states explained.",
    content: "Pending → Paid → Shipped → Delivered → Complete.",
    keywords: ["order", "status", "lifecycle"],
    relationships: [{ targetId: "ship-rw", domain: D.SHIPPING, label: "Delivery" }],
    metadata: buildMetadata({ flow: "standard" }),
    priority: 60,
  }),
  createKnowledgeDocument({
    id: "search-001",
    domain: D.SEARCH,
    title: "Smart search guidelines",
    summary: "How YEBO interprets natural language product queries.",
    content: "Queries map to categories, brands, price ranges, and attributes.",
    keywords: ["search", "query", "smart"],
    metadata: buildMetadata({ searchType: "natural" }),
    priority: 65,
  }),
  createKnowledgeDocument({
    id: "flash-001",
    domain: D.FLASH_SALE,
    title: "Weekend flash sale",
    summary: "Up to 40% off selected footwear — 48 hours only.",
    content: "Limited stock. Automatic discount at checkout.",
    keywords: ["flash", "sale", "discount"],
    relationships: [{ targetId: "prod-001", domain: D.PRODUCT, label: "Premium Running Sneakers" }],
    metadata: buildMetadata({ discount: 40 }),
    priority: 85,
  }),
  createKnowledgeDocument({
    id: "auc-001",
    domain: D.AUCTION,
    title: "Live auction: Vintage watch",
    summary: "Bid ends in 6 hours. Starting bid 25,000 RWF.",
    content: "Authenticated vintage timepiece from verified collector.",
    keywords: ["auction", "bid", "watch"],
    metadata: buildMetadata({ bidEnds: "6h" }),
    priority: 70,
  }),
  createKnowledgeDocument({
    id: "evt-001",
    domain: D.EVENT,
    title: "Spring Sale Event",
    summary: "Marketplace-wide promotional event.",
    content: "Featured vendors, bundle deals, and free shipping thresholds.",
    keywords: ["event", "sale", "spring"],
    relationships: [{ targetId: "flash-001", domain: D.FLASH_SALE, label: "Weekend flash sale" }],
    metadata: buildMetadata({ eventId: "evt-spring" }),
    priority: 80,
  }),
  createKnowledgeDocument({
    id: "sup-001",
    domain: D.SUPPORT,
    title: "Contact support",
    summary: "How to reach Yebone customer support.",
    content: "In-app chat, email support@yebone.com, response within 24 hours.",
    keywords: ["support", "help", "contact"],
    relationships: [{ targetId: "faq-ship", domain: D.FAQ, label: "Shipping FAQ" }],
    metadata: buildMetadata({ channel: "multi" }),
    priority: 55,
  }),
];

export default MOCK_KNOWLEDGE_DOCUMENTS;
